GlobalAssureRSA/GlobalAssure/Controllers/AssistanceController.cs
using CsvHelper;
using GlobalAssure.Entity;
using GlobalAssure.Models;
using GlobalAssure.RelianceRSA;
using log4net;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Device.Location;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.UI.WebControls;
using System.Xml;

namespace GlobalAssure.Controllers
{
    /// <summary>
    /// IndexId     Date            Developer        Desc
    /// 1001        26/11/2019      Bikash           Reliance Service URL Change   
    /// 1002        04/12/2019      Arshad           Added RILAssit Controller
    /// 1003        10/12/2019      Hassan           Changes in Assistance Data Entry Page
    /// 1004        07/01/2020      Arshad           Added Travel Controller
    /// ---------------------------- New Changes -------------------------------------------
    /// 1005        07/03/2020      Hassan           Search Assistance Data by CertificateNo
    /// 1006        12/03/2020      Arshad           Added MIS Controller and View ,  Added Assist Summary in view and binding code in Controller
    /// 1007        16/07/2020      Arshad           Added new Method to show the Assitdetails on New Page and also added method for 3 letter autofill
    ///                                             
    /// </summary>
    public class AssistanceController : Controller
    {

        private GlobalAssureRSAEntities db = new GlobalAssureRSAEntities();
        ILog logger = LogManager.GetLogger("OnlinePayment");
        Communication _c = new Communication();
        GlobalAssureEncryption enc = new GlobalAssureEncryption();

        // GET: Assist
        public ActionResult Index()
        {
            return View();
        }

        //sa 1004
        public ActionResult Travel()
        {
            TravelModel TravelModel = new TravelModel();
            try
            {
                string UserName = Convert.ToString(User.Identity.Name);
                TravelModel = GetAllListItems();
            }
            catch (Exception e)
            {
                HandleException(e);
                throw;
            }

            return View(TravelModel);
        }

        public TravelModel GetAllListItems()
        {
            TravelModel TravelModel = new TravelModel();

            TravelModel.CountryVisitingListItem = db.tblCountryMasterTravelREL.AsNoTracking().Where(w => w.IsValid != false).Select(s => new { s.CountryId, s.CountryName })
                              .ToDictionary(d => d.CountryId, d => d.CountryName);
            TravelModel.StateListItem = db.tblStateMasterREL.AsNoTracking().Where(w => w.IsValid != false).Select(s => new { s.StateId, s.StateName })
                          .ToDictionary(d => d.StateId, d => d.StateName);
            TravelModel.PlanListItem = db.tblMstCommonTypes.AsNoTracking().Where(w => w.MasterType == CrossCutting_Constant.RILTravelPlan && w.IsValid != false).Select(s => new { s.CommonTypeID, s.Description })
                          .ToDictionary(d => d.CommonTypeID, d => d.Description);
            TravelModel.NomRelListItem = db.tblMstCommonTypes.AsNoTracking().Where(w => w.MasterType == CrossCutting_Constant.NomineeRelationship && w.IsValid != false).Select(s => new { s.CommonTypeID, s.Description })
                          .ToDictionary(d => d.CommonTypeID, d => d.Description);
            TravelModel.AgeGroupListItem = db.tblMstCommonTypes.AsNoTracking().Where(w => w.MasterType == CrossCutting_Constant.RILTravelAgeGroup && w.IsValid != false).Select(s => new { s.CommonTypeID, s.Description })
                          .ToDictionary(d => d.CommonTypeID, d => d.Description);
            TravelModel.GenderListItem = db.tblMstCommonTypes.AsNoTracking().Where(w => w.MasterType == CrossCutting_Constant.RILTravelGender && w.IsValid != false).Select(s => new { s.CommonTypeID, s.Description })
                          .ToDictionary(d => d.CommonTypeID, d => d.Description);

            return TravelModel;
        }

        //se 1004
        public ActionResult AssistDataEntry()
        {
            AssistanceDataEntryModel AsstDataEntrymodel = new AssistanceDataEntryModel();
            try
            {
                string UserName = Convert.ToString(User.Identity.Name);
                AsstDataEntrymodel = GetProducts(UserName);
            }
            catch (Exception e)
            {
                HandleException(e);
                throw;
            }

            return View(AsstDataEntrymodel);
        }

        public AssistanceDataEntryModel GetProducts(string UserName)
        {
            int CompanyId = 0;
            string[] ProductsList = ConfigurationManager.AppSettings["AssistanceDataEntryProducts"].ToLower().Split(',');

            AssistanceDataEntryModel AsstDataEntrymodel = new AssistanceDataEntryModel();

            var userdata = db.AspNetUsers.AsNoTracking().Where(w => w.Email == UserName).FirstOrDefault();
            if (userdata != null)
            {
                if (userdata.CompanyID == null)
                {
                    CompanyId = 0;        
                }
                else
                {
                    CompanyId = Convert.ToInt32(userdata.CompanyID);
                }
            }

            AsstDataEntrymodel.PermanentStateListItem = db.tblMstStates.AsNoTracking().Where(w => w.IsValid != false).Select(s => new { s.StateID, s.State })
                              .ToDictionary(d => d.StateID, d => d.State);

            //AsstDataEntrymodel.ProductListItem = db.tblMstProducts.AsNoTracking().Where(w => w.IsValid != false)
            //              .Select(s => new { s.ProductID, s.ProductName }).ToDictionary(d => d.ProductID, d => d.ProductName);

            AsstDataEntrymodel.ProductListItem = db.tblMstProducts.AsNoTracking().Where(w => w.IsValid != false && ProductsList.Contains(w.ProductName.ToLower()))
                          .Select(s => new { s.ProductID, s.ProductName }).ToDictionary(d => d.ProductID, d => d.ProductName);            

            if (CompanyId > 0)
            {
                AsstDataEntrymodel.CompanyListItem = db.tblMstCommonTypes.AsNoTracking().Where(w => w.IsValid != false && w.MasterType == CrossCutting_Constant.Company_Name && w.CommonTypeID == CompanyId)
                                             .Select(s => new { s.CommonTypeID, s.Description }).ToDictionary(d => d.CommonTypeID, d => d.Description);

                AsstDataEntrymodel.CompID = CompanyId;
            }
            else
            {
                AsstDataEntrymodel.CompanyListItem = db.tblMstCommonTypes.AsNoTracking().Where(w => w.IsValid != false && w.MasterType == CrossCutting_Constant.Company_Name)
                                             .Select(s => new { s.CommonTypeID, s.Description }).ToDictionary(d => d.CommonTypeID, d => d.Description);

                AsstDataEntrymodel.CompID = CompanyId;
            }          

            return AsstDataEntrymodel;
        }

        public ActionResult AssistDataEntryWeb()
        {
            AssistanceDataEntryModel AsstDataEntrymodel = new AssistanceDataEntryModel();
            try
            {
                string UserName = Convert.ToString(User.Identity.Name);
                AsstDataEntrymodel = GetProductsWeb(UserName);
            }
            catch (Exception e)
            {
                HandleException(e);
                throw;
            }

            return View(AsstDataEntrymodel);
        }

        public AssistanceDataEntryModel GetProductsWeb(string UserName)
        {
            int CompanyId = 0;
            string[] ProductsList = ConfigurationManager.AppSettings["AssistanceDataEntryProducts"].ToLower().Split(',');

            AssistanceDataEntryModel AsstDataEntrymodel = new AssistanceDataEntryModel();

            var userdata = db.AspNetUsers.AsNoTracking().Where(w => w.Email == UserName).FirstOrDefault();
            if (userdata != null)
            {
                if (userdata.CompanyID == null)
                {
                    CompanyId = 0;
                }
                else
                {
                    CompanyId = Convert.ToInt32(userdata.CompanyID);
                }
            }

            AsstDataEntrymodel.PermanentStateListItem = db.tblMstStates.AsNoTracking().Where(w => w.IsValid != false).Select(s => new { s.StateID, s.State })
                              .ToDictionary(d => d.StateID, d => d.State);

            //AsstDataEntrymodel.ProductListItem = db.tblMstProducts.AsNoTracking().Where(w => w.IsValid != false)
            //              .Select(s => new { s.ProductID, s.ProductName }).ToDictionary(d => d.ProductID, d => d.ProductName);

            AsstDataEntrymodel.ProductListItem = db.tblMstProducts.AsNoTracking().Where(w => w.IsValid != false && ProductsList.Contains(w.ProductName.ToLower()))
                          .Select(s => new { s.ProductID, s.ProductName }).ToDictionary(d => d.ProductID, d => d.ProductName);

            if (CompanyId > 0)
            {
                AsstDataEntrymodel.CompanyListItem = db.tblMstCommonTypes.AsNoTracking().Where(w => w.IsValid != false && w.MasterType == CrossCutting_Constant.Company_Name && w.CommonTypeID == CompanyId)
                                             .Select(s => new { s.CommonTypeID, s.Description }).ToDictionary(d => d.CommonTypeID, d => d.Description);

                AsstDataEntrymodel.CompID = CompanyId;
            }
            else

GlobalAssureRSA/GlobalAssure/Views/Assistance/AssistList.cshtml
@{
    ViewBag.Title = "Search";
    List<SelectListItem> LstStatus = ViewBag.StatusLst;
    SelectListItem sli = new SelectListItem { Value = "0", Text = "--All--" };
    LstStatus.Insert(0, sli);

    }

<h2 class="main-title text-center" style="color:#716f6f !important"></h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <p class="active-class" style="color:#fff"><strong>Search</strong></p>
    </div>
    <div class="width-0 panel-body" style="background-color: #fff">
        <div style="margin:5px 5px 3px 49px">

            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Assist Reference No</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtRefNo" />
                </div>
            </div>

            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Customer First Name</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtCustomerFirstName" />
                </div>
            </div>

            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Customer Last Name</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtCustomerLastName" />
                </div>
            </div>

            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Engine No</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtEngineNo" />
                </div>
            </div>

            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Chassis No</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtChassisNo" />
                </div>
            </div>

            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Customer Contact No</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtCustomerContactNo" />
                </div>
            </div>
            <div class="col-md-4" id="dvEmail">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Customer Email</label>
                    </div>
                    <input type="text" class="form-control" id="txtCustomerEmail">
                </div>
            </div>

            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Issue Date From</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtCertificateIssueDateFrom" />
                </div>
            </div>
            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Issue Date To</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtCertificateIssueDateTo" />
                </div>
            </div>

            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Status</label>
                    </div>
                    @Html.DropDownList("ddlStatus", LstStatus, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-sm-12">
            <div class="col-lg-4 col-sm-4"></div>
            <div class="col-lg-12 col-sm-6 form-group text-center">
                <input type="button" value="Search" id="btnSearch" style="margin:05% 3% 05% 0%" ; class="btn btn-primary" />
                <input type="button" value="Refresh" id="btnRefresh" ; class="btn" />
            </div>
        </div>
    </div>

    <div id="CertificateGrid" style="overflow:auto;"></div>
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-4 col-sm-4"></div>
        <div class="col-lg-12 col-sm-6 form-group text-center">
            <input type="button" value="Download" id="btnDownload" style="margin:05% 3% 05% 0%" ; class="btn btn-primary" />
            @*<input type="button" value="Download MIS Report" id="btnDownloadAssistMISReport" style="margin:05% 3% 05% 0%" ; class="btn btn-primary" />*@
        </div>
    </div>
</div>



<script>

    $('#btnRefresh').click(function () {
        window.location.reload();
    });

    $(document).ready(function () {

        var parameters = new URLSearchParams(window.location.search);
        var param = parameters.get('RefNo');
        $("#txtRefNo").val(param);

        loadGrid();

        $("#btnSearch").click(function () {
            loadGrid();
        });

        function loadGrid() {

            var Registration = '';
            var RefNo = $("#txtRefNo").val();
            var FirstName = $("#txtCustomerFirstName").val();
            var LastName = $("#txtCustomerLastName").val();
            var EngineNo = $("#txtEngineNo").val();
            var ChassisNo = $("#txtChassisNo").val();
            var MobileNo = $("#txtCustomerContactNo").val();
            var EmailID = $("#txtCustomerEmail").val();
            var CertificateIssueDateFrom = $("#txtCertificateIssueDateFrom").val();
            var CertificateIssueDateTo = $("#txtCertificateIssueDateTo").val();
            var statudId = $('#ddlStatus').val();

            $.ajax({
                url: '@Url.Action("SearchAssist", "Assistance")',
                data: { Registration: Registration, RefNo: RefNo, FirstName: FirstName, LastName: LastName, EngineNo: EngineNo, ChassisNo: ChassisNo, MobileNo: MobileNo, CertificateIssueDateFrom: CertificateIssueDateFrom, CertificateIssueDateTo: CertificateIssueDateTo, statusId: statudId, EmailID: EmailID },
                datatype: 'json',
                type: "POST",
                beforeSend: function () {
                    $("#LoadingImage").show();
                },
                success: function (result) {
                    if (result.status == '@CrossCutting_Constant.Success') {
                        $('#CertificateGrid').empty().append(result.Html);
                    }
                    else {
                        AlertMessage("//Please Try Again", "5000", "fail");
                    }
                }
            });
        }

        //////////////////////////////////////////////////////////////////////////////////////

        $("#ddlStatus").each(function () {
            $('option', this).each(function () {
                if ($(this).text().toLowerCase() == "vendor closed issue") {
                    $(this).text("Vendor Closed Issue");
                }                
            });
        });

    });


     $(document).ready(function () {

         $("#btnDownload").click(function () {

             var Registration = '';
             var RefNo = $("#txtRefNo").val();
             var FirstName = $("#txtCustomerFirstName").val();
             var LastName = $("#txtCustomerLastName").val();
             var EngineNo = $("#txtEngineNo").val();
             var ChassisNo = $("#txtChassisNo").val();
             var MobileNo = $("#txtCustomerContactNo").val();
             var EmailId = $("#txtCustomerEmail").val();
             var CertificateIssueDateFrom = $("#txtCertificateIssueDateFrom").val();
             var CertificateIssueDateTo = $("#txtCertificateIssueDateTo").val();
             var statudId = $('#ddlStatus').val();            
             window.location.href = '@Url.Content("~/Assistance/DownloadAssistList?Registration=")' + Registration + '&RefNo=' + RefNo + '&FirstName=' + FirstName + '&LastName=' + LastName + '&EngineNo=' + EngineNo + '&ChassisNo=' + ChassisNo + '&MobileNo=' + MobileNo + '&statusId=' + statudId + '&EmailID=' + EmailId + '&CertificateIssueDateFrom=' + CertificateIssueDateFrom + '&CertificateIssueDateTo=' + CertificateIssueDateTo;
         });


         $("#btnDownloadAssistMISReport").click(function () {

             var Registration = '';
             var RefNo = $("#txtRefNo").val();
             var FirstName = $("#txtCustomerFirstName").val();
             var LastName = $("#txtCustomerLastName").val();
             var EngineNo = $("#txtEngineNo").val();
             var ChassisNo = $("#txtChassisNo").val();
             var MobileNo = $("#txtCustomerContactNo").val();
             var EmailId = $("#txtCustomerEmail").val();
             var CertificateIssueDateFrom = $("#txtCertificateIssueDateFrom").val();
             var CertificateIssueDateTo = $("#txtCertificateIssueDateTo").val();
             var statudId = $('#ddlStatus').val();            
             window.location.href = '@Url.Content("~/Assistance/DownloadAssistMISReport?Registration=")' + Registration + '&RefNo=' + RefNo + '&FirstName=' + FirstName + '&LastName=' + LastName + '&EngineNo=' + EngineNo + '&ChassisNo=' + ChassisNo + '&MobileNo=' + MobileNo + '&statusId=' + statudId + '&EmailID=' + EmailId + '&CertificateIssueDateFrom=' + CertificateIssueDateFrom + '&CertificateIssueDateTo=' + CertificateIssueDateTo;
         });
     });

    $("#txtCertificateIssueDateFrom,#txtCertificateIssueDateTo").each(function () {
        $(this).keypress(function (event) { event.preventDefault(); });
        $(this).bind("paste", function (e) {
            e.preventDefault();
        });
    });


    $("#txtCertificateIssueDateFrom").datepicker({
        todayHighlight: true,
        format: 'dd/mm/yyyy',
        autoclose: true,

    })

    $("#txtCertificateIssueDateTo").datepicker({
        todayHighlight: true,
        format: 'dd/mm/yyyy',
        autoclose: true,
    })
  
</script>

GlobalAssureRSA/GlobalAssure/Views/Assistance/CaseCharges.cshtml
@{
    ViewBag.Title = "SearchAssistancebyCertificateNo";

    List<SelectListItem> CompanyList = ViewBag.CompanyList;
    SelectListItem sliCompany = new SelectListItem { Value = "", Text = "--All--" };
    CompanyList.Insert(0, sliCompany);
}

<h2 class="main-title text-center" style="color:#716f6f !important">Case Charges</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <p class="active-class" style="color:#fff"><strong>Case Charges</strong></p>
    </div>
    <form id="frmSearchAssist">
        <div class="width-0 panel-body" style="background-color: #fff">
            <div style="margin:5px 5px 3px 49px">
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Company Name</label>
                        </div>
                        @Html.DropDownList("ddlCompanyName", CompanyList, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Assist Reference No</label>
                        </div>
                        <input type="text" class="form-control" id="txtRefNo">
                    </div>
                </div>
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>From Date</label>
                        </div>
                        <input type="text" class="form-control removeBackgroundcolor" id="txtFromDate" readonly>
                    </div>
                </div>
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>To Date</label>
                        </div>
                        <input type="text" class="form-control removeBackgroundcolor" id="txtToDate" readonly>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 col-sm-12">
                <div class="col-lg-4 col-sm-4"></div>
                <div class="col-lg-12 col-sm-6 form-group text-center">
                    <input type="button" value="Search" id="btnSearch" style="margin:05% 3% 05% 0%" class="btn btn-primary" />
                    <input type="button" value="Refresh" id="btnRefresh" class="btn" />
                </div>
            </div>
        </div>
    </form>
    <div id="CertificateGrid"></div>
</div>

<script>

    $('#btnRefresh').click(function () {

        window.location.reload();
    });
    

    ///////////////////////////////////// Submit /////////////////////////////////////////
    $(document).ready(function () {  

        var parameters = new URLSearchParams(window.location.search);
        var param = parameters.get('RefNo');
        $("#txtRefNo").val(param);

        var RefNo = $("#txtRefNo").val();
        if (RefNo != "" && RefNo != null) {

            loadGrid(RefNo)
        }
        else {

            RefNo = "";
            loadGrid(RefNo)
        }      

        $("#btnSearch").click(function () {

            loadSearchGrid();
        });
    });

    $("#txtFromDate").datepicker({
        todayHighlight: true,
        format: 'dd/mm/yyyy',
        autoclose: true,

    })

    $("#txtToDate").datepicker({
        todayHighlight: true,
        format: 'dd/mm/yyyy',
        autoclose: true,

    })

    function loadGrid(RefNo) {            

            $.ajax({
                url: '@Url.Action("SearchCase", "Assistance")',
                data: { RefNo: RefNo },
                datatype: 'json',
                type: "POST",
                beforeSend: function () {
                    $("#LoadingImage").show();
                },
                success: function (result) {

                    $('#txtFromDate').val(result.FromDate);
                    $('#txtToDate').val(result.ToDate);

                    if (result.status == '@CrossCutting_Constant.Success') {
                       
                        $('#CertificateGrid').empty().append(result.Html);
                    }
                    else {

                        $('#CertificateGrid').empty();
                        AlertMessage("// " + result.errormessage + "", "5000", "fail");
                    }
                }
            });
        }

    function loadSearchGrid() {

        var CompanyID = $("#ddlCompanyName").val();
        var RefNo = $("#txtRefNo").val();
        var FromDate = $("#txtFromDate").val();
        var ToDate = $("#txtToDate").val();
        var valid = true;
        if (FromDate == '' || ToDate == '') {
            valid = false;
        }
       

        if (valid) {

            $.ajax({

                url: '@Url.Action("SearchCaseCharges", "Assistance")',
                data: { CompanyID: CompanyID, RefNo: RefNo, FromDate: FromDate, ToDate:ToDate},
                datatype: 'json',
                type: "POST",
                beforeSend: function () {

                    $("#LoadingImage").show();
                },
                success: function (result) {

                    if (result.status == '@CrossCutting_Constant.Success' && result.message == '@CrossCutting_Constant.Success') {

                        $('#CertificateGrid').empty().append(result.Html);
                    }
                    else if (result.status == '@CrossCutting_Constant.Success' && result.message == '@CrossCutting_Constant.NoAssistanceFound') {

                        $('#CertificateGrid').empty();
                        AlertMessage("// No Assistance Found", "5000", "fail");
                    }
                    else {

                        $('#CertificateGrid').empty();
                        AlertMessage("// No Data Found", "5000", "fail");
                    }
                }
            });
        }
        else {

            $('#CertificateGrid').empty();
            AlertMessage("// Please Enter From Date / To Date", "5000", "fail");
        }
    }
    

</script>

GlobalAssureRSA/GlobalAssure/Views/Assistance/SearchCertificateGridNextpage.cshtml
@using GridMvc.Html;
@using GridMvc.Html;
@using GridMvc.Pagination
@using GridMvc.Sorting
@using GlobalAssure.Models;


@model Grid.Mvc.Ajax.GridExtensions.AjaxGrid<AssistModel>
@Html.Grid(Model).WithMultipleFilters().Named("SearchCertificateGrid").Columns(columns =>
   {      
       columns.Add(c => c.TransactionID)
   .Titled("View")
  .Sanitized(false).Encoded(false)
   .RenderValueAs(o => Html.ActionLink("View", "GetAssistDetailToEdit", "Assistance",new { TransactionID = o.TransactionID }, htmlAttributes:null));
       columns.Add(c => c.CertificateNo).Titled("Certificate No").Filterable(true);
       columns.Add(c => c.FirstName).Titled("FirstName").Filterable(true);
       columns.Add(c => c.LastName).Titled("LastName").Filterable(true);
       columns.Add(c => c.Make).Titled("Make").Filterable(true);
       columns.Add(c => c.Model).Titled("Model").Filterable(true);
       columns.Add(c => c.RegistrationNo).Titled("Vehicle Registration").Filterable(true);
       columns.Add(c => c.Mobile).Titled("Mobile No").Filterable(true);
       columns.Add(c => c.Email).Titled("Email").Filterable(true);
       columns.Add(c => c.CompanyName).Titled("Company Name").Filterable(true);
   }).WithPaging(10).Filterable(true)

GlobalAssureRSA/GlobalAssure/Views/Assistance/_SearchAssistGridNextPage.cshtml
@using GridMvc.Html;
@using GridMvc.Html;
@using GridMvc.Pagination
@using GridMvc.Sorting
@using GlobalAssure.Models;

@model Grid.Mvc.Ajax.GridExtensions.AjaxGrid<AssistVendroDetail>
@Html.Grid(Model).WithMultipleFilters().Named("SearchAssistGrid").Columns(columns =>
{
    //    columns.Add(c => c.AssistId)
    //.Titled("View/Edit")
    //.Filterable(false).Sanitized(false).Encoded(false)
    //.RenderValueAs(o => Html.ActionLink("View/Edit", "", "", new { @onclick = "GetAssistDetails('" + o.AssistId + "');return false" }).ToHtmlString());
    columns.Add(c => c.AssistId)
.Titled("View/Edit")
.Sanitized(false).Encoded(false)
.RenderValueAs(o => Html.ActionLink("View/Edit", "GetAssistDetailForVendor", "Assistance",new { AssitId = o.AssistId }, htmlAttributes:null));
    columns.Add(c => c.AssistNo)
.Titled("View Audit")
.Filterable(false).Sanitized(false).Encoded(false)
.RenderValueAs(o => Html.ActionLink("View Audit", "", "", new { @onclick = "GetAssistAuditDetails('" + o.AssistId + "');return false" }).ToHtmlString());
    columns.Add(c => c.Registration).Titled("Vehicle Registration").Filterable(true);
    columns.Add(c => c.RefNo).Titled("Reference No").Filterable(true);
    columns.Add(c => c.ContactNo).Titled("Contact No").Filterable(true);
    columns.Add(c => c.CreatedDate).Titled("Reported Date").Filterable(true);
    columns.Add(c => c.Action).Titled("Action").Filterable(true);
    columns.Add(c => c.Status).Titled("Status").Filterable(true);
    columns.Add(c => c.CompanyName).Titled("Company Name").Filterable(true);
    columns.Add(c => c.VendorName).Titled("Vendor Name").Filterable(true);
    columns.Add(c => c.BranchName).Titled("Branch Name").Filterable(true);
    columns.Add(c => c.VendorAssignedDateTime).Titled("Vendor Assign Date/Time").Filterable(true);
    columns.Add(c => c.VendorReachedIncidentLocationDateTime).Titled("Vendor Reached in Incident Location Date/Time").Filterable(true);
    columns.Add(c => c.VendorReachedDropLocationDateTime).Titled("Vendor Reached in Drop Location Date/Time").Filterable(true);
}).WithPaging(10).Filterable(true)