GlobalAssureRSA/GlobalAssure/Controllers/VendorController.cs
using CsvHelper;
using GlobalAssure.Entity;
using GlobalAssure.Models;
using LinqToExcel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GlobalAssure.Controllers
{
    public class VendorController : Controller
    {

        private GlobalAssureRSAEntities db = new GlobalAssureRSAEntities();
        Communication _c = new Communication();

        // GET: Vendor
        public ActionResult Index()
        {
            return View();
        }

        #region SearchAssist
        public JsonResult SearchAssist(string Registration, string RefNo)
        {
            try
            {
                List<AssistVendroDetail> list = new List<AssistVendroDetail>();

                ViewBag.Registration = Registration;
                ViewBag.RefNo = RefNo;

                TempData["Load"] = "FirstTime";
                list = this.GetSearchAssistList(Registration, RefNo);
                var aj = new Grid.Mvc.Ajax.GridExtensions.AjaxGridFactory();
                var Grid = aj.CreateAjaxGrid(list.AsQueryable(), 1, false, 2);
                var Html = RenderPartialViewToString("~/Views/Vendor/_SearchAssistVendorGrid.cshtml", Grid);
                return Json(new { status = CrossCutting_Constant.Success, Html = Html }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                HandleException(e);
                return Json(new { status = CrossCutting_Constant.Failure }, JsonRequestBehavior.AllowGet);
            }
        }

        private List<AssistVendroDetail> GetSearchAssistList(string registration, string refNo)
        {
            List<AssistVendroDetail> list = new List<AssistVendroDetail>();
            string UserName = User.Identity.Name;
            var userdata = db.AspNetUsers.Where(w => w.UserName == UserName).Select(s => new { s.Id, s.IsAdmin, s.TieUpCompanyID }).FirstOrDefault();


            list = (from a in db.tblAssistDetails
                    join branch in db.tblVendorBranchDetails on a.VendorId equals branch.BranchID
                    join t in db.tblTransactions.AsNoTracking() on a.TransactionId equals t.TransactionID
                    join s in db.tblMstWorkFlowStatus.AsNoTracking() on a.StatusId equals s.StatusID into objStatus
                    from status in objStatus.DefaultIfEmpty()
                    join at in db.tblMstWorkFlowStatus.AsNoTracking() on a.ActionId equals at.StatusID into objAction

                    from Action in objAction.DefaultIfEmpty()
                    where ((a.RefNo.Contains(refNo) || string.IsNullOrEmpty(refNo))
                    && (a.StatusId == CrossCutting_Constant.StatusID_Vendor_Assigned)
                    && (branch.userid == userdata.Id)
                    )
                    select new AssistVendroDetail
                    {
                        TransactionID = t.TransactionID,
                        ActionId = (int)a.ActionId,
                        Address = a.Address,
                        CreatedDate = a.CreatedDate,
                        Issue = a.Issue,
                        Landmark = a.Landmark,
                        Lat = a.Lat,
                        Lon = a.Lon,
                        PinCode = a.PinCode,
                        RefNo = a.RefNo,
                        Registration = t.RegistrationNo,
                        Remarks = a.Remarks,
                        Status = status.Status,
                        Action = Action.Status,
                        VendorId = a.VendorId,
                        ContactNo = t.CustomerContact,
                        AssistId = a.Id

                    }).ToList();

            return list;
        }
        #endregion

        #region SearchAssistNextPage
        public ActionResult SearchAssistNextPage(int? Page, string Registration, string RefNo, int SortingOrder = 0, int Paging = 5)
        {
            try
            {
                List<AssistVendroDetail> list = new List<AssistVendroDetail>();
                TempData["Load"] = "FirstTime";
                ViewBag.Registration = Registration;
                ViewBag.RefNo = RefNo;
                list = this.GetSearchAssistList(Registration, RefNo);
                var aj = new Grid.Mvc.Ajax.GridExtensions.AjaxGridFactory();
                var grid = aj.CreateAjaxGrid(list.AsQueryable(), Page.HasValue ? Page.Value : 1, Page.HasValue, 2);
                var Html = RenderPartialViewToString("~/Views/Vendor/_SearchAssistVendorGridNextPage.cshtml", grid);
                return Json(new { status = CrossCutting_Constant.Success, Html = Html, HasItems = grid.HasItems }, JsonRequestBehavior.AllowGet);
            }

            catch (Exception ex)
            {
                HandleException(ex);
                throw;
            }
        }
        #endregion


        public JsonResult GetAssistDetailForVendor(string AssitId)
        {
            string HTML = String.Empty;
            try
            {
                string UserName = HttpContext.User.Identity.Name;
                decimal Assitid = Convert.ToDecimal(AssitId);
                AssistVendroDetail assistDetails = this.GetAssistDetails(Assitid);
                HTML = RenderPartialViewToString("~/Views/Vendor/AssistDetailForVendor.cshtml", assistDetails);
                return Json(new { message = CrossCutting_Constant.Success, HTML = HTML }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                HandleException(ex);
                throw;
            }
        }

        private AssistVendroDetail GetAssistDetails(decimal AssitId)
        {
            AssistVendroDetail data = new AssistVendroDetail();
            tblAssistDetail objTran = db.tblAssistDetails.Where(x => x.Id == AssitId).FirstOrDefault();
            data = (from a in db.tblAssistDetails.AsNoTracking()
                    join t in db.tblTransactions.AsNoTracking() on a.TransactionId equals t.TransactionID
                    join s in db.tblMstWorkFlowStatus.AsNoTracking() on a.StatusId equals s.StatusID into objStatus
                    from status in objStatus.DefaultIfEmpty()
                    join at in db.tblMstWorkFlowStatus.AsNoTracking() on a.ActionId equals at.StatusID into objAction
                    from Action in objAction.DefaultIfEmpty()
                    join inc in db.tblMstIncidentDetails.AsNoTracking() on a.IncidentDetailid equals inc.IncidentDetailid into objincident
                    from Incident in objincident.DefaultIfEmpty()
                    where a.Id == AssitId
                    select new AssistVendroDetail
                    {
                        TransactionID = t.TransactionID,
                        Registration = t.RegistrationNo,
                        ContactNo = t.CustomerContact,
                        ActionId = (int)a.ActionId,
                        Address = a.Address,
                        CreatedDate = a.CreatedDate,
                        Issue = a.Issue,
                        Landmark = a.Landmark,
                        Lat = a.Lat,
                        Lon = a.Lon,
                        PinCode = a.PinCode,
                        RefNo = a.RefNo,
                        Remarks = a.Remarks,
                        StatusId = (int)a.StatusId,
                        VendorId = a.VendorId,
                        Action = Action.Status,
                        Status = status.Status,
                        AssistId = a.Id,
                        VehicleColor = a.VehicleColor,
                        VehicleYear = a.VehicleYear,
                        IncidentDetail = Incident.IncidentDetail,
                        ChasisNo = t.ChassisNo,
                        CustomerName = t.CustomerName,
                        EngineNo = t.EngineNo,
                        Make = t.tblMstMake.Name,
                        Model = t.tblMstModel.Name,
                        RegistrationNo = t.RegistrationNo,
                        CertificateNo = t.CertificateNo,
                        CertificateStartDate = t.CoverStartDate,
                        CertificateEndDate = t.CoverEndDate,
                        StsId = (int)a.StatusId

                    }).FirstOrDefault();

            data.lstAction = db.tblMstWorkFlowStatus.Where(x => x.Module == 2).Select(x =>
                new SelectListItem { Text = x.Status, Value = x.StatusID.ToString() }).ToList();

            data.lstStatus = db.tblMstWorkFlowStatus.Where(x => x.Module == 1 && x.StatusID != 8).Select(x =>
                new SelectListItem { Text = x.Status, Value = x.StatusID.ToString() }).ToList();

            return data;

        }

        public JsonResult SaveAssistVendorData(AssistVendroDetail data)
        {
            string AssistanceCompletionToVendorBody = ConfigurationManager.AppSettings["AssistanceCompletionToVendorBody"];
            string AssistanceCompletionToCustomerBody = ConfigurationManager.AppSettings["AssistanceCompletionToCustomerBody"];
            string Message = string.Empty;
            bool MsgSent = false;

            tblAssistDetail objTbl = db.tblAssistDetails.Where(x => x.Id == data.AssistId).FirstOrDefault();

            var vendata = (from vbd in db.tblVendorBranchDetails.AsNoTracking()
                           join v in db.tblMstVendors.AsNoTracking() on vbd.VendorID equals v.VendorID into objVendorBased
                           from objVendor in objVendorBased.DefaultIfEmpty()
                           where vbd.BranchID == objTbl.VendorId
                           select new
                           {
                               VendorMobileNo = objVendor.VendorMobileNo

                           }).FirstOrDefault();

GlobalAssureRSA/GlobalAssure/Views/Vendor/AssistDetailForVendor.cshtml
@model GlobalAssure.Models.AssistVendroDetail

<style>
    .ClaimDetailDialogMain-dialog .modal-dialog {
        width: 90%;
        overflow: auto;
    }

    .bootstrap-dialog.type-primary .modal-header {
        background-color: #32419c;
    }
    /*.ClaimDetailDialogMain-dialog  .modal-backdrop{
            z-index:1040 !important;
        }*/
    .modal-backdrop {
        z-index: 1040 !important;
    }
</style>
@using (Html.BeginForm("", "", FormMethod.Post, new { Id = "frmVendorAssist" }))
{

    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="active-class" style="color:#fff"><strong>Incident Details</strong></p>
        </div>
        <div class="width-0 panel-body" style="background-color: #fff">
            <div>
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Reference No</label>
                        </div>
                        @Html.TextBoxFor(x => x.RefNo, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Incident Details</label>
                        </div>
                        @Html.TextBoxFor(x => x.IncidentDetail, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Mobile No/ Additional Details</label>
                        </div>
                        @Html.TextAreaFor(x => x.Issue, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Street Address</label>
                        </div>
                        @Html.TextBoxFor(x => x.StreetAddress, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Landmark</label>
                        </div>
                        @Html.TextBoxFor(x => x.Landmark, new { @class = "form-control  ", @readonly = "readonly" })
                    </div>
                </div>
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Address</label>
                        </div>
                        @Html.TextAreaFor(x => x.Address, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Pin Code</label>
                        </div>
                        @Html.TextBoxFor(x => x.PinCode, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>




                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Location</label>
                        </div>
                        @Html.TextBoxFor(x => x.location, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>City</label>
                        </div>
                        @Html.TextBoxFor(x => x.City, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>
                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Contact No</label>
                        </div>
                        @Html.TextBoxFor(x => x.ContactNo, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>


                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Certificate No</label>
                        </div>
                        @Html.TextBoxFor(x => x.CertificateNo, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Certificate Start Date</label>
                        </div>
                        @Html.TextBoxFor(x => x.CertificateStartDate, "{0:dd/MM/yyyy}", new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Certificate End Date</label>
                        </div>
                        @Html.TextBoxFor(x => x.CertificateEndDate, "{0:dd/MM/yyyy}", new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Vehicle Make</label>
                        </div>
                        @Html.TextBoxFor(x => x.Make, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Registration No</label>
                        </div>
                        @Html.TextBoxFor(x => x.Registration, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Vehicle Model</label>
                        </div>
                        @Html.TextBoxFor(x => x.Model, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Vehicle Year</label>
                        </div>
                        @Html.TextBoxFor(x => x.VehicleYear, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Vehicle Color</label>
                        </div>
                        @Html.TextBoxFor(x => x.VehicleColor, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Engine No</label>
                        </div>
                        @Html.TextBoxFor(x => x.EngineNo, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Chasis No</label>
                        </div>
                        @Html.TextBoxFor(x => x.ChasisNo, new { @class = "form-control ", @readonly = "readonly" })
                    </div>
                </div>




                @Html.HiddenFor(x => x.StatusId)

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Action</label>
                        </div>
                        @Html.DropDownListFor(x => x.ActionId, Model.lstAction, new { @class = "form-control" })
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Upload Invoice</label>
                        </div>
                        <input type="file" />
                    </div>
                </div>

                <div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Status</label>
                        </div>
                        @Html.DropDownListFor(x => x.StsId, Model.lstStatus, new { @class = "form-control" })
                    </div>
                </div>

            </div>
            @Html.HiddenFor(x => x.AssistId)


            <div class="col-lg-12 col-sm-12">
                <div class="col-lg-4 col-sm-4"></div>
                <div class="col-lg-12 col-sm-6 form-group text-center">
                    <input type="button" value="Submit" id="btnSaveAssist" style="margin:05% 3% 05% 0%" ; class="btn btn-primary" />
                </div>
            </div>
        </div>

    </div>


}
<script>

    $('#btnSaveAssist').click(function () {

        var valid = $('#frmVendorAssist').validationEngine('validate')

        if (valid) {
            $.ajax({
                url: '@Url.Action("SaveAssistVendorData", "Vendor")',
                data: $('#frmVendorAssist').serialize(),
                type: "POST",
                beforeSend: function () {
                    $("#LoadingImage").show();
                },
                success: function (result) {
                    var assistreftag = "";
                    var message = "";

                    if (result.message == '@CrossCutting_Constant.Success') {
                        AlertMessage("//updated successfully", "5000", "suc");
                        window.location.href = "../../Vendor/Index";
                        dialog.close();
                    }
                    else {

                        alert("Error")
                    }

                }

            });


        }

    });

</script>

GlobalAssureRSA/GlobalAssure/Views/Vendor/AssistMIS.cshtml
@{
    ViewBag.Title = "Assist MIS";
}

<style>
    .panel-heading {
        background-image: linear-gradient(to bottom, #00529C 0%, #e8e8e8 100%);
        padding: 5px !important;
        color: #fff;
        font-size: 16px;
    }
</style>



<link href="https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet" />
<script src="~/Scripts/jquery-ui.js"></script>


<h2 class="main-title text-center" style="color:#716f6f !important">Assist MIS Report</h2>


<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title" style="color:#fff">
            <strong>Assist MIS Report</strong>
        </h1>
    </div>

    <div class="row no-padding">
        <div style="margin:5px 5px 3px 49px" class="col-md-12">

            <div class="width-100" style="background-color: #fff">

                <div class="col-lg-12 col-sm-12">
                    <div class="col-lg-4 col-sm-4"></div>
                    <div class="col-lg-12 col-sm-6 form-group text-center">
                        <input type="button" class="btn btn-primary" style="margin:05% 3% 05% 0%" value="Download" name="" id="btnAssistReport">

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>



<script>



    $(document).ready(function () {
        ///////////////////////////////////// Submit /////////////////////////////////////////
        $("#btnAssistReport").click(function () {

            window.location.href = '@Url.Content("~/Vendor/DownloadAssistMISReport")'
        });

    });



</script>

GlobalAssureRSA/GlobalAssure/Views/Vendor/Index.cshtml
@{
    ViewBag.Title = "Search";
}

<h2 class="main-title text-center" style="color:#716f6f !important"></h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <p class="active-class" style="color:#fff"><strong>Search</strong></p>
    </div>
    <div class="width-0 panel-body" style="background-color: #fff">
        <div style="margin:5px 5px 3px 49px">


            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Assist Reference No</label>
                    </div>
                    <input type="text" class="form-control removeBackgroundcolor" id="txtRefNo" />
                </div>
            </div>

            @*<div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Vehicle Registration No</label>
                        </div>
                        <input type="text" class="form-control removeBackgroundcolor" id="txtRegistrationNo" />
                    </div>
                </div>*@

            @*<div class="col-md-4">
                    <label><span>&nbsp;</span></label>
                    <div class="form-group">
                        <div>
                            <label>Mobile No</label>
                        </div>
                        <input type="text" class="form-control removeBackgroundcolor" id="txtMobile" />
                    </div>
                </div>*@
        </div>
        <div class="col-lg-12 col-sm-12">
            <div class="col-lg-4 col-sm-4"></div>
            <div class="col-lg-12 col-sm-6 form-group text-center">
                <input type="button" value="Search" id="btnSearch" style="margin:05% 3% 05% 0%" ; class="btn btn-primary" />
                <input type="button" value="Refresh" id="btnRefresh" ; class="btn" />
            </div>
        </div>
    </div>

    <div id="CertificateGrid"></div>
</div>



<script>

    $('#btnRefresh').click(function () {
        window.location.reload();
    });

    $(document).ready(function () {

        loadGrid();

        $("#btnSearch").click(function () {
            loadGrid();
        });

        function loadGrid() {
            var Registration = '';
            var RefNo = $("#txtRefNo").val();

            $.ajax({
                url: '@Url.Action("SearchAssist", "Vendor")',
                data: { Registration: Registration, RefNo: RefNo },
                datatype: 'json',
                type: "POST",
                beforeSend: function () {
                    $("#LoadingImage").show();
                },
                success: function (result) {
                    if (result.status == '@CrossCutting_Constant.Success') {
                        $('#CertificateGrid').empty().append(result.Html);
                    }
                    else {
                        AlertMessage("//Please Try Again", "5000", "fail");
                    }
                }
            });
        }

        //////////////////////////////////////////////////////////////////////////////////////

    });

</script>

GlobalAssureRSA/GlobalAssure/Views/Vendor/SearchBranchs.cshtml
@{
    ViewBag.Title = "Search Vendor";
}

<h2 class="main-title text-center" style="color:#716f6f !important"></h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <p class="active-class" style="color:#fff"><strong>Search Branch</strong></p>
    </div>
    <div class="width-0 panel-body" style="background-color: #fff">
        <div style="margin:5px 5px 3px 49px">


            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Branch Name</label>
                    </div>
                    <input type="text" class="form-control" id="txtBranchName" />
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-sm-12">
            <div class="col-lg-4 col-sm-4"></div>
            <div class="col-lg-12 col-sm-6 form-group text-center">
                <input type="button" value="Search" id="btnSearch" style="margin:05% 3% 05% 0%" ; class="btn btn-primary" />
                <input type="button" value="Refresh" id="btnRefresh" ; class="btn" />
            </div>
        </div>
    </div>

    <div id="BranchGrid"></div>
</div>



<script>

    $('#btnRefresh').click(function () {
        window.location.reload();
    });

    $(document).ready(function () {

        loadGrid();

        $("#btnSearch").click(function () {
            loadGrid();
        });

        function loadGrid() {

            var BranchName = $("#txtBranchName").val();

            $.ajax({
                url: '@Url.Action("SearchBranch", "Vendor")',
                data: { BranchName: BranchName },
                datatype: 'json',
                type: "POST",
                beforeSend: function () {
                    $("#LoadingImage").show();
                },

                success: function (result) {
                    $('#BranchGrid').html(result);
                }
            });
        }

        //////////////////////////////////////////////////////////////////////////////////////

    });

</script>

GlobalAssureRSA/GlobalAssure/Views/Vendor/SearchVendors.cshtml
@{
    ViewBag.Title = "Search Vendor";
}

<h2 class="main-title text-center" style="color:#716f6f !important"></h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <p class="active-class" style="color:#fff"><strong>Search Vendor</strong></p>
    </div>
    <div class="width-0 panel-body" style="background-color: #fff">
        <div style="margin:5px 5px 3px 49px">


            <div class="col-md-4">
                <label><span>&nbsp;</span></label>
                <div class="form-group">
                    <div>
                        <label>Vendor Name</label>
                    </div>
                    <input type="text" class="form-control" id="txtVendorName" />
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-sm-12">
            <div class="col-lg-4 col-sm-4"></div>
            <div class="col-lg-12 col-sm-6 form-group text-center">
                <input type="button" value="Search" id="btnSearch" style="margin:05% 3% 05% 0%" ; class="btn btn-primary" />
                <input type="button" value="Refresh" id="btnRefresh" ; class="btn" />
            </div>
        </div>
    </div>

    <div id="VendorGrid"></div>
</div>



<script>

    $('#btnRefresh').click(function () {
        window.location.reload();
    });

    $(document).ready(function () {

        loadGrid();

        $("#btnSearch").click(function () {
            loadGrid();
        });

        function loadGrid() {

            var VendorName = $("#txtVendorName").val();

            $.ajax({
                url: '@Url.Action("SearchVendor", "Vendor")',
                data: { VendorName: VendorName },
                datatype: 'json',
                type: "POST",
                beforeSend: function () {
                    $("#LoadingImage").show();
                },

                success: function (result) {
                    $('#VendorGrid').html(result);
                }
            });
        }

        //////////////////////////////////////////////////////////////////////////////////////

    });

</script>