GlobalAssureRSA/GlobalAssure/Controllers/WebPortalController.cs
using CsvHelper;
using Fonet;
using GlobalAssure.Entity;
using GlobalAssure.Models;
using LinqToExcel;
using log4net;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Core.Objects;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Xsl;
using System.Text.RegularExpressions;
using iTextSharp.text.pdf;
using iTextSharp.text;

namespace GlobalAssure.Controllers
{
    public class WebPortalController : Controller
    {
        private GlobalAssureRSAEntities db = new GlobalAssureRSAEntities();
        ILog logger1 = LogManager.GetLogger("OnlinePayment");
        Communication _c = new Communication();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        HomeController objHome = new HomeController();
        AssistanceController objAssist = new AssistanceController();

        // GET: PolicyBazaar
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Error(string Error)
        {
            ViewBag.Error = Error;
            return View();
        }

        #region issueCertificate
        public async System.Threading.Tasks.Task<ActionResult> issueCertificate(string data)
        {
            TransactionModel model = new TransactionModel();
            GlobalAssureEncryption enc = new GlobalAssureEncryption();
            CertificateRequest request = new CertificateRequest();
            // Request Parameter Samples
            // string encriptMessage = enc.Encrypt("FName=Virat&LName=Kohli&Email=sharafudheen@inubesolutions.com&Mobile=9999999999&Make=KTM&Model=DUKE&Reg=KA01KH1234&User=policyBazaar&Pass=Assist@123");

            string DecriptMessage = enc.Decrypt(data);
            string[] SplitMessage = DecriptMessage.Split('&');
            string[] para = new string[10];

            for (int i = 0; i < SplitMessage.Length; i++)
            {
                string[] str = SplitMessage[i].Split('=');
                para[i] = str[1];
            }

            request.FName = para[0] == "" ? null : para[0];
            request.LName = para[1] == "" ? null : para[1];
            request.Email = para[2] == "" ? null : para[2];
            request.Mobile = para[3] == "" ? null : para[3];
            request.Make = para[4] == "" ? null : para[4];
            request.Model = para[5] == "" ? null : para[5];
            request.Reg = para[6] == "" ? null : para[6];
            request.User = para[7] == "" ? null : para[7];
            request.Password = para[8] == "" ? null : para[8].TrimStart('\0');
            request.MName = para[9] == "" ? null : para[9].TrimStart('\0');
            try
            {
                if (string.IsNullOrEmpty(request.User) || string.IsNullOrEmpty(request.Password))
                {

                    ViewBag.Error = "Invalid User";
                    return View("~/Views/WebPortal/Error.cshtml");
                }
                else
                {
                    bool validUser = await isValidUser(request.User, request.Password);

                    if (validUser)
                    {
                        //    string.IsNullOrEmpty(request.Mobile) || string.IsNullOrEmpty(request.Make) || string.IsNullOrEmpty(request.Model)
                        //|| string.IsNullOrEmpty(request.Reg) ||

                        string UserName = request.User;
                        string ValidRequest = string.Empty;

                        model = GetIssueCertificate(UserName, request.Make, request.Model, ref ValidRequest);
                        model.CustomerName = request.FName;
                        model.CustomerMiddleName = request.MName;
                        model.CustomerLastName = request.LName;
                        model.CustomerContact = request.Mobile;
                        model.CustomerEmail = request.Email;
                        model.RegistrationNo = request.Reg;
                        model.IssueByID = CrossCutting_Constant.IssueBy_Application_ID;
                        return View(model);
                    }
                    else
                    {

                        ViewBag.Error = "Invalid User";
                        return View("~/Views/WebPortal/Error.cshtml");


                    }
                }
            }
            catch (Exception e)
            {
                HandleException(e);
                throw;
            }


        }
        #endregion

        #region SaveIssueCertificate
        [HttpPost]
        public ActionResult SaveIssueCertificate(TransactionModel transmodel)
        {
            bool IsPayNow = false;
            bool onlinePay = false;
            string CertificateNo = "";
            string PaymentRefNo = "";
            string Path = "";



            vPayOnlinePaymentResponseModel vPayResponse = new vPayOnlinePaymentResponseModel();
            try
            {
                if (ModelState.IsValid)
                {

                    DateTime CurrentDate = DateTime.Now;
                    tblTransaction model = new tblTransaction();
                    tblTransactionAuditLog audit = new tblTransactionAuditLog();
                    tblChequeAuditLog chequeaudit = new tblChequeAuditLog();
                    var productname = db.tblMstProducts.AsNoTracking().Where(w => w.ProductID == transmodel.ProductID).Select(s => s.ProductName).FirstOrDefault();

                    string UserName = User.Identity.Name;
                    AspNetUser userdata = db.AspNetUsers.Where(w => w.UserName == UserName).FirstOrDefault();

                    ObjectParameter Output = new ObjectParameter("UniqueCode", typeof(string));
                    var UniqueCodeNo = db.usp_UniqeNumberGeneration(CrossCutting_Constant.CertificatePrefix, "", "", "", "", "", Output);
                    model.CertificateNo = Convert.ToString(productname) + Convert.ToString(Output.Value);

                    model.IssueByID = transmodel.IssueByID;
                    model.UserID = userdata.Id;
                    model.CreatedDate = CurrentDate;
                    model.IsValid = true;
                    model.ProductID = transmodel.ProductID;
                    model.PlanID = transmodel.PlanID;
                    model.MakeID = transmodel.MakeID;
                    model.ModelID = transmodel.ModelID;
                    model.EngineNo = transmodel.EngineNo;
                    model.ChassisNo = transmodel.ChassisNo;
                    model.RegistrationNo = transmodel.RegistrationNo;
                    model.RegistrationDate = transmodel.RegistrationDate;
                    model.CustomerName = transmodel.CustomerName;
                    model.CustomerMiddleName = transmodel.CustomerMiddleName;
                    model.CustomerLastName = transmodel.CustomerLastName;
                    model.CustomerEmail = transmodel.CustomerEmail;
                    model.CustomerContact = transmodel.CustomerContact;
                    // Start date
                    if (userdata.RiskStartCount > 0)
                    {
                        int RiskStartCount = userdata.RiskStartCount;
                        string RiskDate = Convert.ToString(transmodel.CoverStartDate);
                        DateTime RiskStartDate = Convert.ToDateTime(RiskDate);
                        model.CoverStartDate = RiskStartDate.AddDays(RiskStartCount);
                    }
                    else
                    {
                        model.CoverStartDate = transmodel.CoverStartDate;
                    }
                    
                   //End Date
                    if (userdata.RiskStartCount > 0)
                    {
                        int RiskStartCount = userdata.RiskStartCount;
                        string RiskDate = Convert.ToString(transmodel.CoverEndDate);
                        DateTime RiskEndDate = Convert.ToDateTime(RiskDate);
                        model.CoverEndDate = RiskEndDate.AddDays(RiskStartCount);
                    }
                    else
                    {
                        model.CoverEndDate = transmodel.CoverEndDate;
                    }


                    model.IssueDate = CurrentDate;

                    if (transmodel.ChkIsSameAsPermanentAddress)
                    {
                        model.PermanentCityID = transmodel.PermanentCityID;
                        model.PermanentAddress = transmodel.PermanentAddress;
                        model.PermanentAddress2 = transmodel.PermanentAddress2;
                        model.PermanentAddress3 = transmodel.PermanentAddress3;
                        model.PermanentLandmark = transmodel.PermanentLandmark;
                        model.CommunicationCityID = transmodel.PermanentCityID;
                        model.CommunicationAddress = transmodel.PermanentAddress;
                        model.CommunicationAddress2 = transmodel.PermanentAddress2;
                        model.CommunicationAddress3 = transmodel.PermanentAddress3;
                        model.CommunicationLandmark = transmodel.PermanentLandmark;
                        model.IsSameAsPermanentAddress = true;
                    }
                    else
                    {
                        model.PermanentCityID = transmodel.PermanentCityID;
                        model.PermanentAddress = transmodel.PermanentAddress;
                        model.PermanentAddress2 = transmodel.PermanentAddress2;
                        model.PermanentAddress3 = transmodel.PermanentAddress3;
                        model.PermanentLandmark = transmodel.PermanentLandmark;

GlobalAssureRSA/GlobalAssure/Views/WebPortal/AssistanceResponse.cshtml
@{

    Layout = "~/Views/Shared/_LayoutPolicyBazaar.cshtml";
    ViewBag.Title = "AssistanceReponse";
}

GlobalAssureRSA/GlobalAssure/Views/WebPortal/EBikeOTPVerification.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPolicyBazaar.cshtml";
    ViewBag.Title = "E-Bike OTP Verification";
}

@using (Html.BeginForm("", "", FormMethod.Post, new { Id = "EBikeOTPForm" }))
{
    <h2 class="main-title text-center" style="color:#716f6f !important">E-Bike OTP Verification</h2>
    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="active-class" style="color:white"><img src="~/Image/Site/Forma 1.png" />Enter Mobile No for OTP Verification</p>
        </div>
        <div class="width-100 panel-body" style="background-color: #fff">
            <div style="margin:5px 5px 3px 49px">
                <div class="row no-padding">
                    <div class="col-md-12 text-center">
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>Mobile No</label>
                                    <span class="mandatory">*</span>
                                </div>
                                <input type="text" class="form-control allow_only_numbers validate[required] validate[custom[integer],maxSize[10],minSize[10],custom[sumIsZero]]" maxlength="10" id="txtMobileNo" autocomplete="off">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                <input type="button" value="Send OTP" id="btnSendOTP" class="btn btn-primary" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-padding">
                    <div class="col-md-12 text-center">
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>OTP</label>
                                    <span class="mandatory">*</span>
                                </div>
                                <input type="text" class="form-control allow_only_numbers validate[required] validate[custom[integer],maxSize[4],minSize[4]]" maxlength="4" id="txtOTP" autocomplete="off">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                <input type="button" value="Validate OTP" id="btnValidateOTP" class="btn btn-primary" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label><span>&nbsp;</span></label>
                            <div class="form-group">
                                <div>
                                    <label>&nbsp;</label>
                                </div>
                                &nbsp;
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<script>

    $("#btnSendOTP").click(function () {

        $("#txtMobileNo").addClass("validate[required]");
        $("#txtOTP").removeClass("validate[required]");

        var valid = $("#EBikeOTPForm").validationEngine('validate');
        if (valid) {

            var MobileNo = $("#txtMobileNo").val();
            if (MobileNo == null || MobileNo == "") {

                AlertMessage("// Mobile No is Mandatory Field.", "5000", "fail");
                return false;
            }

            $.ajax({

                url: '@Url.Action("EBikeSendOTP", "WebPortal")',
                data: { strMobileNo: MobileNo },
                datatype: 'json',
                type: "POST",
                beforeSend: function () {

                    $("#LoadingImage").show();
                },
                success: function (result) {

                    if (result.status == '@CrossCutting_Constant.Success') {

                        var message = "";

                        message = message + "OTP Sent Successfully.";

                        BootstrapDialog.show({

                            type: BootstrapDialog.TYPE_SUCCESS,
                            draggable: true,
                            closable: false,
                            title: "Success",
                            message: message,
                            buttons: [{

                                label: 'OK',
                                action: function (dialog) {

                                    dialog.close();
                                }
                            }]
                        });
                    }
                    else {

                        //AlertMessage("// " + result.errormessage, "5000", "fail");

                        var message = "";

                        message = message + result.errormessage;

                        BootstrapDialog.show({

                            type: BootstrapDialog.TYPE_SUCCESS,
                            draggable: true,
                            closable: false,
                            title: "Failure",
                            message: message,
                            buttons: [{

                                label: 'OK',
                                action: function (dialog) {

                                    dialog.close();
                                }
                            }]
                        });                        
                    }
                }
            });
        }
        else {

            $("#EBikeOTPForm").validationEngine('validate');
        }     
    });


    $("#btnValidateOTP").click(function () {

        $("#txtMobileNo").addClass("validate[required]");
        $("#txtOTP").addClass("validate[required]");

        var valid = $("#EBikeOTPForm").validationEngine('validate');
        if (valid) {

            var MobileNo = $("#txtMobileNo").val();
            var OTP = $("#txtOTP").val();
            if ((MobileNo == null || MobileNo == "") &&
                (OTP == null || OTP == "")) {

                AlertMessage("// Mobile No and OTP is Mandatory Field.", "5000", "fail");
                return false;
            }

            $.ajax({

                url: '@Url.Action("EBikeValidateOTP", "WebPortal")',
                data: { strMobileNo: MobileNo, strOTP: OTP },
                datatype: 'json',
                type: "POST",
                beforeSend: function () {

                    $("#LoadingImage").show();
                },
                success: function (result) {

                    if (result.status == '@CrossCutting_Constant.Success') {

                        var message = "";

                        message = message + "OTP Validate Successfully.";

                        BootstrapDialog.show({

                            type: BootstrapDialog.TYPE_SUCCESS,
                            draggable: true,
                            closable: false,
                            title: "Success",
                            message: message,
                            buttons: [{

                                label: 'OK',
                                action: function (dialog) {

                                    window.location.href = "../../WebPortal/EBikeDataUpload";
                                    dialog.close();
                                }
                            }]
                        });
                    }
                    else {

                        //AlertMessage("// " + result.errormessage, "5000", "fail");

                        var message = "";

                        message = message + result.errormessage;

                        BootstrapDialog.show({

                            type: BootstrapDialog.TYPE_SUCCESS,
                            draggable: true,
                            closable: false,
                            title: "Failure",
                            message: message,
                            buttons: [{

                                label: 'OK',
                                action: function (dialog) {

                                    dialog.close();
                                }
                            }]
                        });
                    }
                }
            });
        }
        else {

            $("#EBikeOTPForm").validationEngine('validate');
        }
    });

</script>

GlobalAssureRSA/GlobalAssure/Views/WebPortal/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPolicyBazaar.cshtml";

}
<div style="padding-left: 100px; color:#0ce20c;">
    <h1>Success</h1>
</div>

GlobalAssureRSA/GlobalAssure/Views/WebPortal/IssueCertificateGAWebPortal.cshtml
@model GlobalAssure.Models.IssueCertificateGAWebPortal

@{
    Layout = "~/Views/Shared/_LayoutPolicyBazaar.cshtml";
    ViewBag.Title = "Issue Certificate GAWebPortal";
}

@using (Html.BeginForm("", "", FormMethod.Post, new { Id = "IssueCertificateGAWebPortalForm" }))
{
    @Html.HiddenFor(x => x.UserID, new { @id = "hdn_UserID" })
    @Html.HiddenFor(x => x.Name, new { @id = "hdn_Name" })
    @Html.HiddenFor(x => x.Email, new { @id = "hdn_Email" })
    @Html.HiddenFor(x => x.MobileNo, new { @id = "hdn_MobileNo" })
    @Html.HiddenFor(x => x.RegistrationNo, new { @id = "hdn_RegistrationNo" })
    @Html.HiddenFor(x => x.ProductId, new { @id = "hdn_ProductId" })
    @Html.HiddenFor(x => x.PlanId, new { @id = "hdn_PlanId" })
}


<script>

    ///////////////////////////////////// Submit /////////////////////////////////////////
    $(document).ready(function () {

        $.ajax({

            url: '@Url.Action("SaveIssueCertificateGAWebPortal", "WebPortal")',
            data: $('#IssueCertificateGAWebPortalForm').serialize(),
            datatype: 'json',
            type: "POST",
            beforeSend: function () {

                $("#LoadingImage").show();
            },
            success: function (result) {

                if (result.status == '@CrossCutting_Constant.Success') {

                    var path = "";
                    var message = "";
                    var message1 = "";
                    var paymentreftag = "";

                    if (result.paymentrefno != null && result.paymentrefno != "") {

                        paymentreftag = "Payment Reference Number : <strong>" + result.paymentrefno + "</strong><br/>";
                    }

                    if (result.path != null && result.path != "") {

                        path = result.path.replace("\\", "/");
                        path = path.replace("~", "../..");
                    }

                    if (path != "") {

                        var anchor = "<a href='" + path + "' target='_blank'>Click Here</a>";
                        message = "Certificate Issued Successfully. <br/> Certification Number : <strong>" + result.certificateno + "</strong><br/>" + paymentreftag + " Download OR Print Certificate : " + anchor;
                    }
                    else {

                        message = "Certificate Issued Successfully. <br/> Certification Number : <strong>" + result.certificateno + "</strong><br/>" + paymentreftag + " Certificate Not Generated Yet. To Download Certificate, Go To Download Menu..";
                    }

                    if (result.IsPayNow) {

                        if (result.vPayResponse.Flag) {

                            window.location.href = result.vPayResponse.vPayTransactionURL;
                        }
                        else {

                            message1 = message1 + "<br/> " + result.vPayResponse.Response;
                            message1 = message1 + "<br/> Sorry!..Unable to process the payment request."

                            BootstrapDialog.show({

                                type: BootstrapDialog.TYPE_SUCCESS,
                                draggable: true,
                                closable: false,
                                title: "Success",
                                message: message1,
                                buttons: [{
                                    label: 'OK',
                                    action: function (dialog) {

                                        //window.location.href = "../../WebPortal/IssueCertificateGAWebPortal";
                                        dialog.close();
                                    }
                                }]
                            });
                        }
                    }
                    else {

                        message1 = "Sorry!..Unable to process the payment request.";

                        BootstrapDialog.show({

                            type: BootstrapDialog.TYPE_SUCCESS,
                            draggable: true,
                            closable: false,
                            title: "Success",
                            message: message1,
                            buttons: [{
                                label: 'OK',
                                action: function (dialog) {

                                    //window.location.href = "../../WebPortal/IssueCertificateGAWebPortal";
                                    dialog.close();
                                }
                            }]
                        });
                    }
                }
                else {

                    AlertMessage("// ErrorMessage : " + result.ErrMsg + "", "5000", "fail");
                }
            }
        });
    });
    //////////////////////////////////////////////////////////////////////////////////////

</script>

GlobalAssureRSA/GlobalAssure/Views/WebPortal/OnlinePaymentResponse.cshtml
@model GlobalAssure.Models.OnlinePaymentResponseModel

@{
    Layout = "~/Views/Shared/_LayoutPolicyBazaar.cshtml";
    ViewBag.Title = "Thank You";
}

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default" id="pnlOfficeDetails">
        <div class="panel-heading" role="tab" id="headingOne">
            @*<h5 class="panel-title text-left">
                    <i class="icon-home"></i>
                    <a data-toggle="collapse" data-target="#collapseOne">
                        Online Payment
                    </a>
                </h5>*@
        </div>

        <div id="collapseOne" class="panel-collapse in" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">

                @if (Model.Status == CrossCutting_Constant.Success)
                {
                    <h1 class="main-title">Thank You</h1>
                    <p> Payment Completed Succesfully, Payment Reference Number : @Model.PaymentReferenceNo</p>
                }
                else
                {
                    <h5 class="main-title">Sorry!..Unable to Process the request  : @Model.Remark </h5>
                }
                <div class="col-lg-16 col-sm-16">
                    <div class="col-lg-8 col-sm-8" style="margin-left:300px;">
                        @*<input type="button" value="Home" class="btn btn-primary req-btn-me" style="width:100px;" id="btnClear" onclick="GoHome()" />*@
                        @if (Model.Status == CrossCutting_Constant.Success && Convert.ToBoolean(TempData["payLater"]) == false && !string.IsNullOrEmpty(Model.CertificateNo))
                        {
                            <input type="button" value="Download Certificate" class="btn btn-primary req-btn-me" style="width:200px;" id="btnClear" onclick="GoCertificate('@Model.CertificateNo','@Model.CertificatePath','@Model.PaymentReferenceNo')" />
                        }

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    @*function GoHome() {
        window.location.href = '@Url.Content("~/Home/Index")';
    }*@

    function GoBacktoPayment() {
        var url = "/Home/MakePayment";
        window.location.href = url;
    }
    function GoCertificate(certificateno, path, paymentreftag) {

        if (path != null && path != "") {
            path = path.replace("\\", "/");
            path = path.replace("~", "../..");
        }
        var anchor = "<a href='" + path + "' target='_blank'>Click Here</a>";
        message = "Certificate Issued Successfully. <br/> Certification Number : <strong>" + certificateno + "</strong><br/>" + paymentreftag + " Download OR Print Certificate : " + anchor;


        BootstrapDialog.show({
            type: BootstrapDialog.TYPE_SUCCESS,
            draggable: true,
            closable: false,
            title: "Success",
            message: message,
            //buttons: [{
            //    label: 'OK',
            //    action: function (dialog) {
            //        window.location.href = "../../Home/IssueCertificate";
            //        dialog.close();
            //    }
            //}]
        });

    }




</script>